DROP TABLE TB_USER;
CREATE TABLE TB_USER (
    USER_ID VARCHAR(10) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    USER_NAME VARCHAR(20) NOT NULL,
    REFRESH_TOKEN VARCHAR(200),
    PRIMARY KEY(USER_ID)
)

INSERT INTO TB_USER VALUES ('WCARD', 'user0101!!', '우리카드', '');